name: Build for macOS

on:
  push:
    tags:
      - 'v*' # Запускать при создании тегов (например: v1.0.0)
  workflow_dispatch: # Разрешить ручной запуск

jobs:
  build-mac:
    runs-on: macos-latest # Используем macOS runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Используйте вашу версию Node.js
        cache: 'npm'
        cache-dependency-path: apps/desktop/package-lock.json

    - name: Install dependencies
      run: |
        npm ci
        cd apps/desktop && npm ci

    - name: Build Electron app for macOS
      run: |
        cd apps/desktop
        npm run build:mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: apps/desktop/dist/*.dmg
        if-no-files-found: error
