name: Build for macOS

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: apps/desktop/package-lock.json

    - name: Cache Electron
      uses: actions/cache@v3
      with:
        path: ~/.cache/electron
        key: ${{ runner.os }}-electron-${{ hashFiles('apps/desktop/package.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-

    - name: Install dependencies
      run: |
        npm ci
        cd apps/desktop && npm ci

    - name: Build Electron app
      run: |
        cd apps/desktop
        npm run build:mac

    - name: List build artifacts
      run: |
        cd apps/desktop/dist
        ls -la

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: apps/desktop/dist/*.dmg

    - name: Upload ZIP artifact (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: macos-zip
        path: apps/desktop/dist/*.zip
        if-no-files-found: ignore
